[package]
name = "aoc-2023-day-11"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.3.0"
boolinator = "2.4.0"
clap = { version = "4.4.11", features = ["derive"] }
itertools = "0.12.0"
